services:
  postgres:
    image: postgres:17
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=main
    ports:
      - '5432:5432'
    volumes:
      - ./db-data:/var/lib/postgresql/data

  redis:
    image: redis:8-alpine
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ./redis-data:/data
  
  redisinsight:
    image: redis/redisinsight:latest
    restart: always
    environment:
      - RI_REDIS_HOST=redis
      - RI_REDIS_PORT=6379
    ports:
      - '5540:5540'
    volumes:
      - ./redisinsight-data:/data
