services:
  postgres:
    image: postgres:17
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=main
    ports:
      - '5432:5432'
    volumes:
      - ./db-data:/var/lib/postgresql/data
